<a href="https://colab.research.google.com/github/nirmal428/Intro-of-Numpy-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## *Intro*




In [ ]:
import numpy as np

1D Aray

In [ ]:
np_array=np.array([1,2,3,4,5])
print(np_array)

[1 2 3 4 5]


2D Array


In [ ]:
np_2D=np.array([[1,2,3],[4,5,6]])
print(np_2D)


[[1 2 3]
 [4 5 6]]


Multi-dimensional Array

In [ ]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## **Array creation method**

Creating Array from Python List

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
#DEFAULT ZEROS VALTUES
arr=np.zeros(3)
print(arr)

[0. 0. 0.]


In [ ]:
#DEFAULT ONE VALTUES
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# SPECIFIC VALUE
arr=np.full((4,3),9)
print(arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]


Creating sequences of number in numpy

In [ ]:
#arange()
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


creating identity matrices

In [ ]:
identity_matrix=np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## **Numpy Array Properties**

**Shape**

In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d.shape)

(2, 3)


**Size**:- total number of element in array

In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d.size)

6


**nidm**:- number of dimensions

In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_3d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr_2d.ndim)
print(arr_3d.ndim)

2
3


.**dtype**:-  return data type

In [ ]:
arr=np.array([1,2,3.0,4,5])
arr_1=np.array([1,2,3,4,5])
print(arr.dtype)
print(arr_1.dtype)

float64
int64


**Data type Changing** --- astype()

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)
new_arr=arr.astype(float)
print(new_arr.dtype)

int64
float64


## **Operaton**

In [ ]:
arr=np.array([1,2,13,4,5])
print(arr+5)
print(arr*5)
print(arr//5)

[ 6  7 18  9 10]
[ 5 10 65 20 25]
[0 0 2 0 1]


## Aggregation

In [ ]:
arr=np.array([1,2,13,4,5])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))

25
5.0
13
1
4.242640687119285
18.0


## **Indexing , Slicing and Fancy Indexing**

access


In [ ]:
#array[index] --> 1D array

arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[0])
print(arr[5])
print(arr[-1])
print(arr[-10])


1
6
10
1


In [ ]:
#array[row,column] --> 2D array
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
print(arr[1,2])

2
6


Slicing --> array(star,stop,step)

In [ ]:
arr=np.array([1,2,3,4,5,6,77,88,99,100,200])
print(arr[1:6])
print(arr[:10])
print(arr[::3])
print(arr[-1])
print(arr[-10:-1])

[2 3 4 5 6]
[  1   2   3   4   5   6  77  88  99 100]
[  1   4  77 100]
200
[  2   3   4   5   6  77  88  99 100]


Fancy Indexing

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[[0,4,9]])
print(arr[[2,4,6,8]])

[ 1  5 10]
[3 5 7 9]


## **Condition**

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[arr>4])

[ 5  6  7  8  9 10]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[arr%2])

[2 1 2 1 2 1 2 1 2 1]


## **reshape()**

reshaping does't create copy. It return view

In [ ]:
reshaped=arr.reshape(2,5)
print(reshaped)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped=arr.reshape(2,2,3)
print(reshaped)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## **Flattening Array**



1.   .ravel() --> it return view (means modificaton are accur)

2.   .flatten() -->return copy modification(original array not affected )



In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d.flatten())   #not affected original array
print(arr_2d.ravel())   #modify original array


[1 2 3 4 5 6]
[1 2 3 4 5 6]


## **Reshapimg & Manipulating Array**

**insert** :--
Create an other array , original array unchanged  

In [ ]:
#insert in 1D Array

#array
#index -
#value -
#asix -
#axis = 0 , row wise data inser
#axis = 1 , column wise data inser


arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr2=np.insert(arr,3,99,axis=0)
print(arr)
print(arr2)


[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3 99  4  5  6  7  8  9 10]


In [ ]:
#inset in 2D Array

arr=np.array([[1,2],[3,4]])
#insert a new row index 1
arr2=np.insert(arr,1,[5,6],axis=0)
print(arr)
print()
print(arr2)
print()
arr3=np.insert(arr2,2,[15,16],axis=0)
print(arr3)

[[1 2]
 [3 4]]

[[1 2]
 [5 6]
 [3 4]]

[[ 1  2]
 [ 5  6]
 [15 16]
 [ 3  4]]


**Append**:-- Create an other array , original array unchanged  

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr2=np.append(arr,99)
print(arr)
print()
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]

[ 1  2  3  4  5  6  7  8  9 10 99]


**Concatenate**  --: join arrays

In [ ]:
# axis 0 --> vertical stacking
# asix 1 --> horizontal stacking

arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr3=np.concatenate((arr1,arr2),axis=0)
print(arr3)

[1 2 3 4 5 6 7 8]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr3=np.concatenate((arr1,arr2),axis=0)
print(arr3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr3=np.concatenate((arr1,arr2),axis=1)
print(arr3)

[[1 2 5 6]
 [3 4 7 8]]


**Removing** :-- delete()

In [ ]:
# removing an specific index number value
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr2=np.delete(arr,3)
print(arr)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  5  6  7  8  9 10]


In [ ]:
#REMOVING IN 2D ARRAY
arr=np.array([[1,2,3],[4,5,6]])
arr2=np.delete(arr,0,axis=1)
print(arr)
print()
print(arr2)

[[1 2 3]
 [4 5 6]]

[[2 3]
 [5 6]]


In [ ]:
#REMOVING IN 2D ARRAY
arr=np.array([[1,2,3],[4,5,6]])
arr2=np.delete(arr,0,axis=0)
print(arr)
print()
print(arr2)

[[1 2 3]
 [4 5 6]]

[[4 5 6]]


**Stacking** combine array vertically OR horizontally

In [ ]:
# vstack()
#hstack()

arr=np.array([1,2,3,4])
arr2=np.array([11,12,13,14])
arr3=np.vstack((arr,arr2))
print(arr3)
print()
arr4=np.hstack((arr,arr2))
print(arr4)

[[ 1  2  3  4]
 [11 12 13 14]]

[ 1  2  3  4 11 12 13 14]


**Splitting** --> Array divide into multiple subArray

In [ ]:
# np.split()  -->  equal
# np.hsplit()   --> Horizontal split
# np.vsplit()  --> Vertical split  (Work only with 2 or more dimention)

arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr2=np.split(arr,2)
print(arr2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr2=np.hsplit(arr,2)
print(arr2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


## **Brodcasting & Vectorization**

**Brodcasting ** --> describes how NumPy treats arrays with different shapes during arithmetic operations.

In [ ]:
prices=[100,200,300]

discount=10

final_price=[]
for price in prices:
  final_priceS=price-(price*discount/100)
  final_price.append(final_priceS)
print(final_price)

#NOT EFFICIENT METHOD

[90.0, 180.0, 270.0]


In [ ]:
# USING BRODCASTING METHOD
import numpy as np
prices=np.array([100,200,300])
discount = 10
final_price=prices-(prices*discount/100)
print(final_price)

[ 90. 180. 270.]


In [ ]:
arr=np.array([100,200,300])
res=arr*2
print(res)

[200 400 600]


In [ ]:
matrix=np.array([[1,2,3],[4,5,6]])
vector =np.array([10,20,30])
res=matrix+vector
print(res)

[[11 22 33]
 [14 25 36]]


**Vectorization** --> apply Operation on each element of array without using LOOP

In [ ]:
ist1=[1,2,3]
ist2=[4,5,6]

res=[x+y for x,y in zip(ist1,ist2)]
print(res)

#that's slow process

[5, 7, 9]


In [ ]:
list1=np.array([1,2,3])
list2=np.array([44,55,66])
res=list1+list2
print(res)

[45 57 69]


In [ ]:
list1=np.array([1,2,3])
res=list1*4
print(res)

[ 4  8 12]


## **Handling Missing & Special Values**

**Missing value** --> Three Builtin Function are there



*   **np.isnan()**  -> detect missing value
*   **np.nan_to_num()** --> missing value replace by an other number


*   **np.isinf()** -->detect infinity number







In [ ]:
#isnan()

arr=np.array([1,2,np.nan,4,np.nan,6])
print(arr)
print(np.isnan(arr))

[ 1.  2. nan  4. nan  6.]
[False False  True False  True False]


In [ ]:
#nan_to_num()

arr=np.array([1,2,np.nan,4,np.nan,6])
print(arr)
print(np.isnan(arr))
print(np.nan_to_num(arr))    #nan default value = 0
print(np.nan_to_num(arr,nan=10))   #nan value = 10



[ 1.  2. nan  4. nan  6.]
[False False  True False  True False]
[1. 2. 0. 4. 0. 6.]
[ 1.  2. 10.  4. 10.  6.]


In [ ]:
#isinf()
#10^1000  OR 1/0

arr=np.array([1,2,np.inf,4,-np.inf,6])
print(arr)
print(np.isinf(arr))

[  1.   2.  inf   4. -inf   6.]
[False False  True False  True False]


In [ ]:
#replace infinity number to finite numbe

arr=np.array([1,2,np.inf,4,-np.inf,6])
print(arr)
print(np.isinf(arr))

clean_arr=np.nan_to_num(arr,posinf=1000,neginf=-1000)  #replace -infinity (-1000) and +infinity(100)
print(clean_arr)

[  1.   2.  inf   4. -inf   6.]
[False False  True False  True False]
[    1.     2.  1000.     4. -1000.     6.]
